name: dp261-g1
channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip

  # notebooks / jupyter
  - jupyterlab
  - notebook
  - ipykernel
  - nbconvert
  - nbformat
  - ipywidgets
  - jupyterlab_widgets
  - widgetsnbextension

  # base data stack
  - numpy
  - pandas
  - scipy
  - python-dateutil
  - pytz

  # visualization
  - matplotlib
  - seaborn
  - plotly
  - kaleido

  # ml
  - scikit-learn=1.7.2
  - imbalanced-learn
  - joblib

  # tuning / advanced models
  - optuna
  - xgboost
  - lightgbm

  # explainability / dashboard
  - shap
  - streamlit

  # files / I/O
  - openpyxl
  - pyarrow

  # versioning / config
  - dvc
  - dvc-gdrive
  - pyyaml

  # optional but useful for notebooks/debug
  - tqdm
