name: dp261-g1
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  # notebooks / jupyter
  - jupyterlab
  - notebook
  - ipykernel
  - nbconvert
  - nbformat
  - ipywidgets
  - jupyterlab_widgets
  - widgetsnbextension

  # base data stack
  - numpy
  - pandas
  - scipy
  - python-dateutil
  - pytz

  # visualization
  - matplotlib
  - seaborn
  - plotly

  # ml
  - scikit-learn
  - imbalanced-learn
  - joblib

  # files / I/O
  - openpyxl
  - pyarrow

  # versioning / config
  - dvc
  - pyyaml

  # optional but useful for notebooks/debug
  - tqdm
