name: build-api

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build API image
        run: docker build -f api/Dockerfile -t dp261-badbuy-api .
